### ISSUE TITLE
Open Formulieren - Zandbak omgeving updaten naar laatst vrijegegeven systeemversie

### ISSUE THREAD

**Issue by StefSchots1993** [Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening#177]
***Als***
PO van open formulieren 

***Wil ik***
wil ik graag dat Open Formulieren in de Zandbak omgeving van ATOS altijd worde bijgewerkt naar de laatste "vrijgegeven" systeem versie zodat de omgeving altijd de laatste functionaliteiten en securityupdates voldoet.
***Zodat***
Wanneer ik de omgeving gebruik altijd beschik over de meest up-to-date versie.

**Comment by StefSchots1993** [comment]
2.0.1. is de laatst vrijgegeven versie, de Zandbakomgeving draait nog op 1.1.7.

**Comment by Snijhuis** [comment]
Is een issue voor ZACbacklog omdat daar de integratie issues ook staan voor CG componenten. Dit issue sluit ik.

Zie issue in ZAC backlog --> https://github.com/NL-AMS-LOCGOV/zaakafhandelcomponent/issues/1985
