### ISSUE TITLE
EPIC: Mijn acties 

### ISSUE THREAD

**Issue by HilbrandHurtak** [Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening#67]
***Als*** Inwoner/bedrijf

***Wil ik*** de door mij uitgevoerde acties en uit te voeren acties in Mijn Loket kunnen bekijken

***Zodat*** ik weet wat ik nog moet voordat de gemeente mijn zaak/aanvraag verder kan behandelen(denk bijvoorbeeld aan nog af te ronden/afgeronde aanvraagformulieren of externe taken)
#4

**Comment by Snijhuis** [comment]
duplicaat van #54
