### ISSUE TITLE
EPIC: uitleg en ondersteuning bij de inrichting van verschillende componenten

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [Dimpact-Samenwerking/Dimpact-Platform-voor-Dienstverlening#81]
***Als*** gemeente

***Wil ik*** duidelijke uitleg en ondersteuning bij de inrichting van verschillende componenten

***Zodat*** beheerders in staat zijn het platform te beheren.

**Comment by Snijhuis** [comment]
Duplicaat van #78 . Deze gesloten
